AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation stack to automate transcription of MP4, MP3, and WAV audio using Amazon Transcribe.

Parameters:
  InputBucketName:
    Type: String
    Description: "The name of the input S3 bucket for audio files (MP4, MP3, WAV)"
  OutputBucketName:
    Type: String
    Description: "The name of the output S3 bucket for transcription results"
  LogBucketName:
    Type: String
    Description: "The name of the S3 bucket for storing logs"

Resources:
  # S3 Bucket for Input Files (MP4, MP3, WAV)
  TranscribeS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties: 
      BucketName: !Ref InputBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256  # Enforce AES256 encryption
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 1  # Expire input files after 1 day
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucketName
        LogFilePrefix: "transcribe-access-logs/"
      Tags:
        - Key: Workload
          Value: Transcription

  # S3 Bucket for Transcription Output
  TranscribeOutputBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref OutputBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256  # Enforce AES256 encryption
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 1  # Expire output files after 1 day
      Tags:
        - Key: Workload
          Value: Transcription

  # S3 Bucket for Logging
  TranscribeS3LogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref LogBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256  # Enforce AES256 encryption for logging bucket
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 2  # Expire logs after 2 days
      Tags:
        - Key: Workload
          Value: Transcription

  # IAM Role for Lambda Function to Access S3 and Transcribe
  TranscribeLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TranscribeLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: 
                  - !Sub "arn:aws:s3:::${InputBucketName}/*"
                  - !Sub "arn:aws:s3:::${OutputBucketName}/*"
              - Effect: Allow
                Action:
                  - transcribe:StartTranscriptionJob
                  - transcribe:GetTranscriptionJob
                Resource: "*"
      Tags:
        - Key: Workload
          Value: Transcription

  # Lambda Function for Audio Transcription Trigger
  TranscribeLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: "TranscribeAudioFunction"
      Handler: index.handler
      Role: !GetAtt TranscribeLambdaRole.Arn
      Runtime: python3.9
      Timeout: 600
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          import logging

          s3 = boto3.client('s3')
          transcribe = boto3.client('transcribe')
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def handler(event, context):
              logger.info(f"Received event: {json.dumps(event)}")
              try:
                  bucket = event['Records'][0]['s3']['bucket']['name']
                  key = event['Records'][0]['s3']['object']['key']

                  audio_file_uri = f"s3://{bucket}/{key}"
                  job_name = key.split('.')[0]
                  output_bucket = os.environ['OUTPUT_BUCKET']
                  media_format = key.split('.')[-1]

                  supported_formats = ['mp4', 'mp3', 'wav']
                  if media_format not in supported_formats:
                      raise Exception(f"Unsupported media format: {media_format}")

                  response = transcribe.start_transcription_job(
                      TranscriptionJobName=job_name,
                      Media={'MediaFileUri': audio_file_uri},
                      MediaFormat=media_format,
                      LanguageCode='en-US',
                      OutputBucketName=output_bucket
                  )
                  logger.info(f"Started transcription job {job_name}")
                  return {
                      'statusCode': 200,
                      'body': json.dumps(f"Started transcription job {job_name}")
                  }
              except Exception as e:
                  logger.error(f"Error processing file {key} in bucket {bucket}: {str(e)}")
                  raise e
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref OutputBucketName

  # Lambda Log Group Retention Policy
  TranscribeLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${TranscribeLambda}"
      RetentionInDays: 3  # Updated to a valid value

Outputs:
  InputS3Bucket:
    Description: "S3 bucket to upload MP4, MP3, WAV files"
    Value: !Ref TranscribeS3Bucket
  
  OutputS3Bucket:
    Description: "S3 bucket where transcription results will be stored"
    Value: !Ref TranscribeOutputBucket

  LambdaFunctionARN:
    Description: "ARN of the Transcription Lambda Function"
    Value: !GetAtt TranscribeLambda.Arn
